sudo: required 
services: 
  - docker
 
before_install:
  - docker build -t ianwang4/docker-react -f Dockerfile.dev .

install:
  - travis_wait 15 mvn install

script:
  - docker run ianwang4/docker-react npm run test -- --coverage